CODE SEGMENT
        ASSUME CS:CODE
START:
        MOV AH,02H
        MOV BH,00H
        MOV DH,03H
        MOV DL,0EH
        INT 10H
        MOV AH,0AH
        MOV AL,'A'
        MOV CX,0001H
        INT 10H
        MOV AH,02H
        MOV DH,04H
        MOV DL,0AH
        INT 10H
        MOV AH,02H
        MOV DH,04H
        MOV DL,0AH
        INT 10H
        MOV AH,02H
        MOV DH,04H
        MOV DL,0AH
        INT 10H
        MOV AH,0AH
        MOV AL,'A'
        MOV CX,0001H
        INT 10H
        MOV AH,02H
        MOV DH,04H
        MOV DL,0EH
        INT 10H
        MOV AH,0AH
        MOV AL,'A'
        MOV CX,0001H
        INT 10H
        MOV AH,02H
        MOV DH,04H
        MOV DL,12H
        INT 10H
        MOV AH,0AH
        MOV AL,'A'
        MOV CX,0001H
        INT 10H
        MOV AH,02H
        MOV DH,05H
        MOV DL,08H
        INT 10H
        MOV AH,0AH
        MOV AL,'A'
        MOV CX,0001H
        INT 10H
    MOV AH,02H
        MOV DH,05H
        MOV DL,0CH
        INT 10H
        MOV AH,0AH
        MOV AL,'A'
        MOV CX,0001H
        INT 10H
        MOV AH,02H
        MOV DH,05H
        MOV DL,10H
        INT 10H
        MOV AH,0AH
        MOV AL,'A'
        MOV CX,0001H
        INT 10H
        MOV AH,02H
        MOV DH,05H
        MOV DL,14H
        INT 10H
    MOV AH,0AH
        MOV AL,'A'
        MOV CX,0001H
        INT 10H
        MOV AH,4CH
        INT 21H
CODE ENDS
END

